config/routes.rb
Guorj::Application.routes.draw do

  root 'home#index'
  match '/signup',   to: 'users#signup',     via: 'get'
  match '/user/:id', to: 'users#show',       via: 'get'
  match '/users',    to: 'users#create',     via: 'post'
  match '/users',    to: 'users#index',      via: 'get'
  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/about',    to: 'home#about',       via: 'get'

  resources :articles do
    collection do
      post :preview
    end
  end
  resources :ings
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :site_configs#, only: [:index, :edit]

end

app/models/site_config.rb
# 在数据库中的配置信息
# 在这里存放 关于 页脚等可能随时改变的的内容
# 使用方法
# SiteConfig.foo
# SiteCofnig.foo = "asdfghjkl"
#
class SiteConfig
  include Mongoid::Document
  include Mongoid::Timestamps

  field :key, type: String
  field :value, type: String

  index key: 1

  validates_presence_of :key
  validates_uniqueness_of :key

  default_scope -> { desc(:updated_at) }

  def self.method_missing(method, *args)
    method_name = method.to_s
    super(method, *args)
  rescue NoMethodError
    if method_name =~ /=$/ 
      var_name = method_name.gsub('=', '')
      value = args.first.to_s
      #save
      if item = self.find_by_key(var_name)
        item.update_attribute(:value, value)
      else
        SiteConfig.create(key: var_name, value: value)
      end
    else
      #item = self.find_by_key(method)? item.value : nil
      if item = self.find_by_key(method)
        item.value
      else
        nil
      end
    end
  end 

  def self.find_by_key(key)
    self.where(key: key.to_s).first
  end

  def self.save_default(key, value)
    self.create(key: key, value: value.to_s) unless find_by_key(key)
  end
end

app/controllers/site_configs_controller.rb
class SiteConfigsController < ApplicationController
  before_action :set_site_config, only: [:show, :edit, :update]
  before_action :signed_in_user
  before_action :admin_user

  def index
    @site_configs = SiteConfig.all
  end

  def show
  end

  def edit
  end

  def update
    if @site_config.update_attributes(params[:site_config].permit!)
      redirect_to site_config_path(params[:id]), notice: '保存成功.'
    else
      render acton: 'edit'
    end
  end

  private
    def set_site_config
      @site_config = SiteConfig.find(params[:id])
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def site_config_params
      params.require(:site_config).permit(:value)
    end
end

app/helpers/site_configs_helper.rb
module SiteConfigsHelper
end

app/views/site_configs/_form.html.erb
<div>
  <%= form_for @site_config, html: {class: "form-horizontal", role: "form"} do |f| %>
    <h1>更新配置</h1>
    <hr />
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <label class="control-label">Key</label>
      <span class="form-control"><%= @site_config.key %></span>
    </div>

    <div class="form-group">
      <label class="control-label">说明</label>
      <%= f.text_area :value, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit '修改', class: "btn btn-primary btn-large" %>
    </div>
  <% end %>
</div>

app/views/site_configs/edit.html.erb
<%= render 'form' %> 

<%= content_for :styles do %>
  <%= stylesheet_link_tag "site_configs", media: "all" %>
<% end %>

app/views/site_configs/index.html.erb
<h1>设置项</h1>
<div class="list">
  <% @site_configs.each do |site_config| %> 
    <div class="cell panel">
      <div class="config_key">键: <%= link_to site_config.key, site_config_path(site_config) %></div>
      <hr />
      <div class="config_value"><pre><%= site_config.value %></pre></div>
    </div> 
  <% end %>
</div>

<%= content_for :styles do %>
  <%= stylesheet_link_tag 'site_configs', media: 'all' %>
<% end %>

app/views/site_configs/show.html.erb
<div class="panel">
  <div class="content">
    <div class="panel">
      <div class="config_key">
        <%= @site_config.key %>
      </div>
      <hr />
      <div class="config_value">
        <pre><%= @site_config.value %></pre>
      </div>
      <div class="config_footer small">
        <span>创建时间:<%= @site_config.created_at.localtime.to_s(:db) %></span>
        <span>更新时间:<%= @site_config.updated_at.localtime.to_s(:db) %></span>
        <%= link_to '编辑', edit_site_config_path(@site_config) %>
        <%= link_to '返回', site_configs_path %>
      </div>
    </div>
  </div>
</div>

<%= content_for :styles do %>
  <%= stylesheet_link_tag 'site_configs', media: 'all' %>
<% end %>