config/routes.rb
Guorj::Application.routes.draw do

  root 'home#index'
  match '/signup',   to: 'users#signup',     via: 'get'
  match '/user/:id', to: 'users#show',       via: 'get'
  match '/users',    to: 'users#create',     via: 'post'
  match '/users',    to: 'users#index',      via: 'get'
  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/about',    to: 'home#about',       via: 'get'

  resources :articles do
    collection do
      post :preview
    end
  end
  resources :ings
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :site_configs#, only: [:index, :edit]

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  WillPaginate.per_page = 10

  #field :user_id, type:Mongoid::Id 
  field :title,   type: String
  field :content, type: String

  index user_id: 1

  belongs_to :user

  default_scope -> { desc(:created_at) }
  #default_scope -> { order('created_at DESC') }

  validates_presence_of :user_id, :title, :content
  validates :content, length: 0..65535
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :edit, :create, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /preview_article.json
  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    #@article = Article.new(article_params)
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: {class: "form-horizontal", role: "form"} do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <div><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</div>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="edit_content">
      <ul id="edit_tab" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#edit_article" role="tab" data-toggle="tab">编辑</a></li>
        <li role="presentation"><a href="#preview_article" role="tab" data-toggle="tab">预览</a></li>
      </ul>
      <div class="tab-content tab-border">
        <div id="edit_article" role="tabpanel" class="tab-pane fade active in">
          <%= f.text_area :content, rows: 25, class: 'form-control' %>
        </div>
        <div id="preview_article" role="tabpanel" class="tab-pane fade">
          <div id="preview_view">加载预览中...</div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "发布", class: "btn btn-primary btn-large" %>
  </div>
<% end %>

<%= content_for :scripts do %>
  <%= javascript_include_tag "articles", 'data-turbolinks' => true %>
<% end %>

app/views/articles/edit.html.erb
<h1>更新文章</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

<%= content_for :styles do %>
  <%= stylesheet_link_tag 'articles', media: 'all' %>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, '文章') %>
<div class="list">
  <% @articles.each do |article| %>
    <div class="cell panel">
      <div class="row">
        <div class="col-md-9">
          <%= link_to article.title, article, class: "title", title: article.title %>
        </div>
        <div class="col-md-3">
          <div class="pull-right small">
            <% if article.updated_at > article.created_at %>
              <div title="<%= article.updated_at.localtime.to_s(:db) %>"><%= time_ago_in_words article.updated_at.localtime.to_s(:db) %></div>
            <% else %>
              <div title="<%= article.created_at.localtime.to_s(:db) %>"><%= time_ago_in_words article.created_at.localtime.to_s(:db) %></div>
            <% end %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @articles %>

<%= content_for :styles do %>
  <%= stylesheet_link_tag "articles" %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

<%= content_for :styles do %>
  <%= stylesheet_link_tag 'articles', media: 'all' %>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="content">
  <div class="panel">
    <div class="article_title">
      <%= @article.title %> 
    </div>
    <div class="inner">
      <div class="article_content">
       <%= markdown @article.content %> 
      </div>
    <div class="article_footer small">
    <div class="posted_time">
      <% if @article.updated_at > @article.created_at %>
        更新时间:<%= @article.updated_at.localtime.to_s(:db) %>
      <% else %>
        创建时间:<%= @article.created_at.localtime.to_s(:db) %>
      <% end %>
      <% if signed_in? %>
        <%= link_to '编辑', edit_article_path(@article) %>
        <%= link_to '删除', @article, method: :delete, data: {confirm: '确定要删除吗?'} %>
      <% end %>
      <%= link_to '返回', articles_path %>
    </div>
    </div> 
    <div class="action"></div>
    </div>
  </div>
</div>

<%= content_for :styles do %>
  <%= stylesheet_link_tag "articles", media: "all" %>
<% end %>