config/routes.rb
Guorj::Application.routes.draw do

  root 'home#index'
  match '/signup',   to: 'users#signup',     via: 'get'
  match '/user/:id', to: 'users#show',       via: 'get'
  match '/users',    to: 'users#create',     via: 'post'
  match '/users',    to: 'users#index',      via: 'get'
  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/about',    to: 'home#about',       via: 'get'

  resources :articles do
    collection do
      post :preview
    end
  end
  resources :ings
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :site_configs#, only: [:index, :edit]

end

app/models/ing.rb
class Ing
  include Mongoid::Document
  include Mongoid::Timestamps
  WillPaginate.per_page = 20

  field :content, type: String

  belongs_to :user

  default_scope -> { desc(:created_at) }
  validates :content, presence: true, length: 1..65535
end

app/controllers/ings_controller.rb
class IngsController < ApplicationController
  before_action :set_ing, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :edit, :create, :update, :destroy]

  # GET /ings
  # GET /ings.json
  def index
    @ing = Ing.new
    @ings = Ing.paginate(page: params[:page])
  end

  # GET /ings/1
  # GET /ings/1.json
  def show
  end

  # GET /ings/1/edit
  def edit
  end

  # POST /ings
  # POST /ings.json
  def  create
    @ing = current_user.ings.build(ing_params)
    respond_to do |format|
      if @ing.save
        format.html { redirect_to @ing, notice: 'Ing was successfully created.'}
        format.json { render action: 'show', status: :created, location: @ing }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @ing.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /ing/1
  def update
    respond_to do |format|
      if @ing.update(ing_params)
        format.html { redirect_to @ing, notice: 'Ing was successfully created.'}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ings/1
  # DELETE /ings/1.json
  def destroy
    @ing.destroy
    respond_to do |format|
      format.html { redirect_to ings_url }
      format.json { head :no_content }
    end
  end

  private
    def set_ing
      @ing = Ing.find(params[:id])
    end

    def ing_params
      params.require(:ing).permit(:content)
    end
end

app/helpers/ings_helper.rb
module IngsHelper
end

app/views/ings/_form.html.erb
<%= form_for @ing, html: { class: "form-horizontal", role: "form" }, remote: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <!--<%= f.label :content, '内容', class: "control-label" %>-->
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "发布", class: 'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/ings/_item.html.erb
<div class="cell panel">
  <%= ing.content %>
  <span class="small">
    <% if ing.updated_at > ing.created_at %>
      <span title="<%= ing.updated_at.localtime.to_s(:db) %>">
        <%= link_to time_ago_in_words(ing.updated_at.localtime.to_s(:db)), ing %>
      </span>
    <% else %>
      <span title="<%= ing.created_at.localtime.to_s(:db) %>">
        <%= link_to time_ago_in_words(ing.created_at.localtime.to_s(:db)), ing %>
      </span>
    <% end %>
  </span>
</div>

app/views/ings/_notice_message.html.erb
<div class="flash">
<%= link_to 'x', '#', class: 'close', 'data-dismiss' => 'alert' %>
<% if @ing.errors.any? %>
  <div id="error_explanation">
    <div>
      The form contains <%= pluralize(@ing.errors.count, "error") %>.
    </div>
    <ul>
      <% @ing.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div>发布成功</div>
<% end %>
</div>

app/views/ings/create.js.erb
$('#notice').html("<%= escape_javascript(render('notice_message')) %>");
<% if @ing.errors.empty? %>
  var list = $('#list');
  list.prepend("<%= escape_javascript(render('item', ing: @ing)) %>");
  $('#ing_content').val('');
<% end %>

app/views/ings/edit.html.erb
<h1>update ing</h1>

<%= render 'form' %>

<%= link_to 'Show', @ing %>
<%= link_to 'Back', ings_path %>

app/views/ings/index.html.erb
<% provide(:title, '闪存') %>

<div id="notice"></div>

<% if signed_in? %>
  <div class="ing_form">
    <%= render 'form' %>
  </div>
<% end %>

<div id="list" class="list">
  <% @ings.each do |ing| %>
    <%= render('item', ing: ing) %>
  <% end %>
</div>

<%= will_paginate @ings %>

<%= content_for :styles do  %>
  <%= stylesheet_link_tag "ings", media: 'all' %>
<% end %>

app/views/ings/show.html.erb
<div class="panel">
  <div class="content">
    <%= @ing.content %>
  </div>
  <div class="ing_footer small">
    <span>创建时间:<%= @ing.created_at.localtime.to_s(:db) %></span>
    <span>更新时间:<%= @ing.updated_at.localtime.to_s(:db) %></span>
    <% if signed_in? %>
      <%= link_to '编辑', edit_ing_path(@ing) %>
      <%= link_to '删除', @ing, method: :delete, data: { confirm: '确定要删除吗?'} %>
    <% end %>
  </div>
</div>

<%= content_for :styles do %>
  <%= stylesheet_link_tag "ings", media: "all" %>
<% end %>