config/routes.rb
Guorj::Application.routes.draw do

  root 'home#index'
  match '/signup',   to: 'users#signup',     via: 'get'
  match '/user/:id', to: 'users#show',       via: 'get'
  match '/users',    to: 'users#create',     via: 'post'
  match '/users',    to: 'users#index',      via: 'get'
  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/about',    to: 'home#about',       via: 'get'

  resources :articles do
    collection do
      post :preview
    end
  end
  resources :ings
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  resources :site_configs#, only: [:index, :edit]

end

app/views/layouts/_footer.html.erb
<div id="footer" class="container">
  <a href="http://www.miitbeian.gov.cn" target="_blank">京ICP备13046340号</a>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">nil<sup class="beta-icon">Beta</sup></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to '首页', "/" %></li>
        <li><%= link_to '文章', articles_path %></li>
        <li><%= link_to '闪存', ings_path %></li>
        <li><a href="/about">关于</a></li>
      </ul>
      <% if signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "写文章", new_article_path %></li>
          <li id="account-menu" class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Site Config', site_configs_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            </ul>
          </li>
        </ul>
      <% else %>
      <% end %>
    </div>
  </div>
</div> <!--end navbar-->

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="生命不息 折腾不止">
<meta name="author" content="nil">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/meta' %>
  <link rel="shortcut icon" href="favicon.ico">
  <title><%= full_title(yield(:title)) %></title>
  <link href="http://grjsoft.com/libs/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="http://grjsoft.com/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield :styles %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container main">
    <%= notice_message %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <script src="http://grjsoft.com/libs/jquery/jquery-2.1.1.min.js"></script>
  <script src="http://grjsoft.com/libs/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "jquery-ujs" %>
  <%= yield :scripts %>
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57983583-1', 'auto');
  ga('send', 'pageview');
</script>
<% end %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>